### ISSUE TITLE
New ui doesnt allow changing expansion

### ISSUE THREAD

**Issue by Sunnypotato** [GergoHalasz/wowtcIssues#1]
On my tiny iPhone 5s i'm no longer able to change expansions after the ui update.
![7FF786FE-02F8-447B-A28D-AF40E9B03E71](https://github.com/user-attachments/assets/874af81e-ec27-456f-abda-da4f992a6e32)

**Comment by GergoHalasz** [comment]
Thank you for reporting the issue. It has been fixed and app can be updated.
